# Generated by Django 5.2.12 on 2026-03-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentAdmin',
            fields=[
                ('fulfillment_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fulfillment_role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(db_column='Employee_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'FULFILLMENTADMIN',
            },
        ),
        migrations.CreateModel(
            name='ProductAdmin',
            fields=[
                ('product_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_role', models.CharField(max_length=50)),
                ('catalog_review_cycle', models.CharField(max_length=50)),
                ('employee', models.OneToOneField(db_column='Employee_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'PRODUCTADMIN',
            },
        ),
    ]
