# Generated by Django 5.2.12 on 2026-03-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'COLOR',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=50)),
                ('size_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'SIZE',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(db_column='Category_ID', on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
                ('product_admin', models.ForeignKey(db_column='Product_Admin_ID', on_delete=django.db.models.deletion.RESTRICT, to='accounts.productadmin')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.ForeignKey(blank=True, db_column='Color_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color')),
                ('product', models.ForeignKey(db_column='Product_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'db_table': 'PRODUCTIMAGE',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('color', models.ForeignKey(db_column='Color_ID', on_delete=django.db.models.deletion.RESTRICT, to='catalog.color')),
                ('product', models.ForeignKey(db_column='Product_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('size', models.ForeignKey(db_column='Size_ID', on_delete=django.db.models.deletion.RESTRICT, to='catalog.size')),
            ],
            options={
                'db_table': 'VARIANT',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
