# Generated by Django 5.2.12 on 2026-03-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('email_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='Order_ID', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'EMAILLOG',
            },
        ),
    ]
