# Generated by Django 5.2.12 on 2026-03-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready_for_Pickup', 'Ready for Pickup'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('pickup_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_ready_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(db_column='Employee_ID', on_delete=django.db.models.deletion.RESTRICT, to='accounts.employee')),
                ('fulfillment_admin', models.ForeignKey(blank=True, db_column='Fulfillment_Admin_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fulfillmentadmin')),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('orderline_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='Order_ID', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('variant', models.ForeignKey(db_column='Variant_ID', on_delete=django.db.models.deletion.RESTRICT, to='catalog.variant')),
            ],
            options={
                'db_table': 'ORDERLINE',
            },
        ),
    ]
